### ISSUE TITLE
Will there be an english build guide?

### ISSUE THREAD

**Issue by freznel10** [palette-system/az-m5ortho#1]
I just bought the kit from Yushakobo since it's so cool. Are there  plans for writing an English build guide?

**Comment by palette-system** [comment]
We apologize for the delay in replying.
Due to lack of hands, the build guide is currently only in Japanese.
I am glad that overseas people are also interested in purchasing.

**Comment by freznel10** [comment]
It is alright. I already purchased the kit and assembled it. I used google
translate to help me understand the instructions.

**Comment by palette-system** [comment]
It was good that it seemed to be completed.
I would like to consider support in English in the future.
Thank you very much.
